# -- VControle --
# Plugin criado para funcionar com o sistema online Mine.VControle.Com

# Chave de identificação deste Servidor
Secret: '1234567890'

# Configurações do MySQL
MySQL:
  # Ativar o uso do banco de dados?
  use: false
  # Endereço do host
  Host: localhost
  # Porta do banco de dados, Padrão: 3306
  Port: 3306
  # Usuario do banco de dados
  Username: test
  # Senha do Banco de dados
  Password: '123'
  # Nome do Banco de dados
  Database: minecraft

# Idioma: en / br
language: br

# Diferenciar maiusculas de minusculas para os nome dos players armazenados em arquivos.
case_sensitive: false

# Permitir apenas uma mudança de grupo VIP por dia (comando /trocarvip), false: infinitas mudanças.
one_vip_change: true

# Enviar uma broadcastMessage quando alguém ativar um VIP.
usekey_global: false

# Remover Players de grupos VIPs quando não forem VIPs, false: desativa esse recurso.
rvip_unlisted: true

# Número (em minutos) para executar a verificação do tempo VIP.
# 0 [zero] = desativa esse recurso
check_time: 10

logging:
  # Gerar Log quando alguém usar '/usekey [key]'
  usekey: false

# Grupo padrão de membros
default_group: default

# Lista de grupos VIPs
vip_groups:
- vip1
- vip2

# Listar todos os itens da ativação aqui
vip_items:
- vip1,0,264,1,none
- vip1,0,35:3,1,none
- vip1,0,35,1,none
- vip1,0,potion:poison:true:10:1,1,blindness-10:1
- vip1,0,$,1000,none
- vip1,0,xp,10,none
- vip1,0,cmd,say @player Muito bom!
- vip1,0,310-311-312-313,1,protection-4
- vip1,0,msg,Oi @player &3tudo bom&4?
- vip1,0,276,1,sharpness-3-knockback-2-name-&4Legendary @player-desc-&3desc 1-desc-&c@player